@startuml
title Diagrama de Clases Movies
class Usuario {
  +darElTitulo(): void
}

class MovieAPI {
  +buscaPeli(titulo: String): List<Movie>
}

class Movie {
  -id: int
  -titulo: String
  -fechaLanzamiento: String
  -descripcion: String
  -popularidad: float
  -votosPromedio: float
  -cuentaDeVotos: int
  -idioma: String
  -posterPath: String
}
class TMDBClient {
  -baseUrl: String
  -token: String
  +TMDBUsuario(token: String)
  +buscaPeli(titulo: String): List<Movie>
}


@enduml
